# StockSense India - Specialized Finance & Social Lexicon
# Values range from -4.0 (extremely negative) to +4.0 (extremely positive)

finance_lexicon = {
    # --- POSITIVE SIGNALS ---
    "bullish": 3.0, 
    "rally": 2.5, 
    "breakout": 2.5, 
    "surge": 2.5,
    "outperform": 2.8, 
    "upgrade": 2.5, 
    "buyback": 2.2, 
    "dividend": 1.8,
    "beat": 2.2, 
    "strong earnings": 3.0, 
    "margin expansion": 2.5,
    "guidance raised": 3.0, 
    "raises guidance": 3.0, 
    "capex": 1.8,
    "record profit": 3.0, 
    "record revenue": 2.8, 
    "accumulation": 2.5,
    "fii buying": 2.5, 
    "dii buying": 2.2, 
    "short squeeze": 3.0,
    "52-week high": 2.0, 
    "all-time high": 2.5, 
    "overweight": 2.0,
    "promoter buying": 2.5,
    "upper circuit": 2.5,
    "bulk deal": 1.5,
    "rbi rate cut": 2.0,

    # --- NEGATIVE SIGNALS ---
    "bearish": -3.0, 
    "selloff": -2.8, 
    "correction": -2.0,
    "downgrade": -2.5, 
    "underperform": -2.5, 
    "headwinds": -2.0,
    "guidance cut": -3.0, 
    "lowers guidance": -3.0, 
    "margin pressure": -2.5,
    "write-off": -2.8, 
    "default": -3.5, 
    "crash": -3.5,
    "fii outflow": -2.0, 
    "fii selling": -2.5, 
    "debt burden": -2.2,
    "profit warning": -3.0, 
    "revenue miss": -2.8, 
    "earnings miss": -2.8,
    "52-week low": -2.0, 
    "all-time low": -2.5, 
    "underweight": -2.0,
    "insolvency": -3.5, 
    "fraud": -3.5, 
    "penalty": -2.0,
    "lower circuit": -2.5,
    "sebi action": -2.5, 
    "sebi penalty": -2.8,
    "promoter selling": -2.5,
    "block deal": -1.5,
    "rbi rate hike": -1.5,
    "npa": -2.5, 
    "delisting": -3.0,

    # --- SOCIAL / REDDIT SLANG ---
    "to the moon": 3.5,
    "moon": 2.5,
    "bagholder": -2.5,
    "dump": -3.0,
    "pump": 1.5,
    "diamond hands": 2.5,
    "paper hands": -1.5,
    "hodl": 2.0,

    # --- NUANCE & MIXED SIGNALS ---
    "in line with estimates": 0.0,
    "results in line": 0.0,
    "margins contract": -1.5,
    "profit up 2%": 0.5, 
    "flat growth": -0.5,
    "guidance maintained": 0.0,
    "likely to": 0.5,
    "could": 0.3,
    "warns of": -1.5
}
